/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// ActivityStatisticsResultDto
    /// </summary>
    [DataContract(Name = "ActivityStatisticsResultDto")]
    public partial class ActivityStatisticsResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityStatisticsResultDto" /> class.
        /// </summary>
        /// <param name="id">The id of the activity the results are aggregated for..</param>
        /// <param name="instances">The total number of running process instances of this activity..</param>
        /// <param name="failedJobs">The total number of failed jobs for the running instances. **Note**: Will be &#x60;0&#x60; (not &#x60;null&#x60;), if failed jobs were excluded..</param>
        /// <param name="incidents">Each item in the resulting array is an object which contains &#x60;incidentType&#x60; and &#x60;incidentCount&#x60;. **Note**: Will be an empty array, if &#x60;incidents&#x60; or &#x60;incidentsForType&#x60; were excluded. Furthermore, the array will be also empty if no incidents were found..</param>
        /// <param name="varClass">The fully qualified class name of the data transfer object class. The class name might change in future releases..</param>
        public ActivityStatisticsResultDto(string id = default(string), int instances = default(int), int failedJobs = default(int), List<IncidentStatisticsResultDto> incidents = default(List<IncidentStatisticsResultDto>), string varClass = default(string))
        {
            this.Id = id;
            this.Instances = instances;
            this.FailedJobs = failedJobs;
            this.Incidents = incidents;
            this.Class = varClass;
        }

        /// <summary>
        /// The id of the activity the results are aggregated for.
        /// </summary>
        /// <value>The id of the activity the results are aggregated for.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The total number of running process instances of this activity.
        /// </summary>
        /// <value>The total number of running process instances of this activity.</value>
        [DataMember(Name = "instances", EmitDefaultValue = false)]
        public int Instances { get; set; }

        /// <summary>
        /// The total number of failed jobs for the running instances. **Note**: Will be &#x60;0&#x60; (not &#x60;null&#x60;), if failed jobs were excluded.
        /// </summary>
        /// <value>The total number of failed jobs for the running instances. **Note**: Will be &#x60;0&#x60; (not &#x60;null&#x60;), if failed jobs were excluded.</value>
        [DataMember(Name = "failedJobs", EmitDefaultValue = false)]
        public int FailedJobs { get; set; }

        /// <summary>
        /// Each item in the resulting array is an object which contains &#x60;incidentType&#x60; and &#x60;incidentCount&#x60;. **Note**: Will be an empty array, if &#x60;incidents&#x60; or &#x60;incidentsForType&#x60; were excluded. Furthermore, the array will be also empty if no incidents were found.
        /// </summary>
        /// <value>Each item in the resulting array is an object which contains &#x60;incidentType&#x60; and &#x60;incidentCount&#x60;. **Note**: Will be an empty array, if &#x60;incidents&#x60; or &#x60;incidentsForType&#x60; were excluded. Furthermore, the array will be also empty if no incidents were found.</value>
        [DataMember(Name = "incidents", EmitDefaultValue = true)]
        public List<IncidentStatisticsResultDto> Incidents { get; set; }

        /// <summary>
        /// The fully qualified class name of the data transfer object class. The class name might change in future releases.
        /// </summary>
        /// <value>The fully qualified class name of the data transfer object class. The class name might change in future releases.</value>
        [DataMember(Name = "@class", EmitDefaultValue = true)]
        public string Class { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivityStatisticsResultDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Instances: ").Append(Instances).Append("\n");
            sb.Append("  FailedJobs: ").Append(FailedJobs).Append("\n");
            sb.Append("  Incidents: ").Append(Incidents).Append("\n");
            sb.Append("  Class: ").Append(Class).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
