/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// CamundaFormRef
    /// </summary>
    [DataContract(Name = "CamundaFormRef")]
    public partial class CamundaFormRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CamundaFormRef" /> class.
        /// </summary>
        /// <param name="key">The key of the Camunda Form..</param>
        /// <param name="binding">The binding of the Camunda Form. Can be &#x60;latest&#x60;, &#x60;deployment&#x60; or &#x60;version&#x60;..</param>
        /// <param name="varVersion">The specific version of a Camunda Form. This property is only set if &#x60;binding&#x60; is &#x60;version&#x60;..</param>
        public CamundaFormRef(string key = default(string), string binding = default(string), int? varVersion = default(int?))
        {
            this.Key = key;
            this.Binding = binding;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// The key of the Camunda Form.
        /// </summary>
        /// <value>The key of the Camunda Form.</value>
        [DataMember(Name = "key", EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// The binding of the Camunda Form. Can be &#x60;latest&#x60;, &#x60;deployment&#x60; or &#x60;version&#x60;.
        /// </summary>
        /// <value>The binding of the Camunda Form. Can be &#x60;latest&#x60;, &#x60;deployment&#x60; or &#x60;version&#x60;.</value>
        [DataMember(Name = "binding", EmitDefaultValue = true)]
        public string Binding { get; set; }

        /// <summary>
        /// The specific version of a Camunda Form. This property is only set if &#x60;binding&#x60; is &#x60;version&#x60;.
        /// </summary>
        /// <value>The specific version of a Camunda Form. This property is only set if &#x60;binding&#x60; is &#x60;version&#x60;.</value>
        [DataMember(Name = "version", EmitDefaultValue = true)]
        public int? VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CamundaFormRef {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Binding: ").Append(Binding).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
