/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// DecisionDefinitionDiagramDto
    /// </summary>
    [DataContract(Name = "DecisionDefinitionDiagramDto")]
    public partial class DecisionDefinitionDiagramDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DecisionDefinitionDiagramDto" /> class.
        /// </summary>
        /// <param name="id">The id of the decision definition..</param>
        /// <param name="dmnXml">An escaped XML string containing the XML that this decision definition was deployed with. Carriage returns, line feeds and quotation marks are escaped..</param>
        public DecisionDefinitionDiagramDto(string id = default(string), string dmnXml = default(string))
        {
            this.Id = id;
            this.DmnXml = dmnXml;
        }

        /// <summary>
        /// The id of the decision definition.
        /// </summary>
        /// <value>The id of the decision definition.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// An escaped XML string containing the XML that this decision definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.
        /// </summary>
        /// <value>An escaped XML string containing the XML that this decision definition was deployed with. Carriage returns, line feeds and quotation marks are escaped.</value>
        [DataMember(Name = "dmnXml", EmitDefaultValue = true)]
        public string DmnXml { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DecisionDefinitionDiagramDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DmnXml: ").Append(DmnXml).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
