/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// DeploymentDto
    /// </summary>
    [DataContract(Name = "DeploymentDto")]
    public partial class DeploymentDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentDto" /> class.
        /// </summary>
        /// <param name="links">The links associated to this resource, with &#x60;method&#x60;, &#x60;href&#x60; and &#x60;rel&#x60;..</param>
        /// <param name="id">The id of the deployment..</param>
        /// <param name="tenantId">The tenant id of the deployment..</param>
        /// <param name="deploymentTime">The time when the deployment was created..</param>
        /// <param name="source">The source of the deployment..</param>
        /// <param name="name">The name of the deployment..</param>
        public DeploymentDto(List<AtomLink> links = default(List<AtomLink>), string id = default(string), string tenantId = default(string), DateTime? deploymentTime = default(DateTime?), string source = default(string), string name = default(string))
        {
            this.Links = links;
            this.Id = id;
            this.TenantId = tenantId;
            this.DeploymentTime = deploymentTime;
            this.Source = source;
            this.Name = name;
        }

        /// <summary>
        /// The links associated to this resource, with &#x60;method&#x60;, &#x60;href&#x60; and &#x60;rel&#x60;.
        /// </summary>
        /// <value>The links associated to this resource, with &#x60;method&#x60;, &#x60;href&#x60; and &#x60;rel&#x60;.</value>
        [DataMember(Name = "links", EmitDefaultValue = true)]
        public List<AtomLink> Links { get; set; }

        /// <summary>
        /// The id of the deployment.
        /// </summary>
        /// <value>The id of the deployment.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The tenant id of the deployment.
        /// </summary>
        /// <value>The tenant id of the deployment.</value>
        [DataMember(Name = "tenantId", EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// The time when the deployment was created.
        /// </summary>
        /// <value>The time when the deployment was created.</value>
        [DataMember(Name = "deploymentTime", EmitDefaultValue = true)]
        public DateTime? DeploymentTime { get; set; }

        /// <summary>
        /// The source of the deployment.
        /// </summary>
        /// <value>The source of the deployment.</value>
        [DataMember(Name = "source", EmitDefaultValue = true)]
        public string Source { get; set; }

        /// <summary>
        /// The name of the deployment.
        /// </summary>
        /// <value>The name of the deployment.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeploymentDto {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  DeploymentTime: ").Append(DeploymentTime).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
