/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// FormDto
    /// </summary>
    [DataContract(Name = "FormDto")]
    public partial class FormDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FormDto" /> class.
        /// </summary>
        /// <param name="key">The form key..</param>
        /// <param name="camundaFormRef">camundaFormRef.</param>
        /// <param name="contextPath">The context path of the process application. If the task (or the process definition) does not belong to a process application deployment or a process definition at all, this property is not set..</param>
        public FormDto(string key = default(string), CamundaFormRef camundaFormRef = default(CamundaFormRef), string contextPath = default(string))
        {
            this.Key = key;
            this.CamundaFormRef = camundaFormRef;
            this.ContextPath = contextPath;
        }

        /// <summary>
        /// The form key.
        /// </summary>
        /// <value>The form key.</value>
        [DataMember(Name = "key", EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets CamundaFormRef
        /// </summary>
        [DataMember(Name = "camundaFormRef", EmitDefaultValue = false)]
        public CamundaFormRef CamundaFormRef { get; set; }

        /// <summary>
        /// The context path of the process application. If the task (or the process definition) does not belong to a process application deployment or a process definition at all, this property is not set.
        /// </summary>
        /// <value>The context path of the process application. If the task (or the process definition) does not belong to a process application deployment or a process definition at all, this property is not set.</value>
        [DataMember(Name = "contextPath", EmitDefaultValue = true)]
        public string ContextPath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FormDto {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  CamundaFormRef: ").Append(CamundaFormRef).Append("\n");
            sb.Append("  ContextPath: ").Append(ContextPath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
