/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// JobConditionQueryParameterDto
    /// </summary>
    [DataContract(Name = "JobConditionQueryParameterDto")]
    public partial class JobConditionQueryParameterDto : IValidatableObject
    {
        /// <summary>
        /// Comparison operator to be used.
        /// </summary>
        /// <value>Comparison operator to be used.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum Gt for value: gt
            /// </summary>
            [EnumMember(Value = "gt")]
            Gt = 1,

            /// <summary>
            /// Enum Lt for value: lt
            /// </summary>
            [EnumMember(Value = "lt")]
            Lt = 2
        }


        /// <summary>
        /// Comparison operator to be used.
        /// </summary>
        /// <value>Comparison operator to be used.</value>
        [DataMember(Name = "operator", EmitDefaultValue = true)]
        public OperatorEnum? Operator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobConditionQueryParameterDto" /> class.
        /// </summary>
        /// <param name="varOperator">Comparison operator to be used..</param>
        /// <param name="value">Date value to compare with..</param>
        public JobConditionQueryParameterDto(OperatorEnum? varOperator = default(OperatorEnum?), DateTime? value = default(DateTime?))
        {
            this.Operator = varOperator;
            this.Value = value;
        }

        /// <summary>
        /// Date value to compare with.
        /// </summary>
        /// <value>Date value to compare with.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public DateTime? Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobConditionQueryParameterDto {\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
