/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// MetricsIntervalResultDto
    /// </summary>
    [DataContract(Name = "MetricsIntervalResultDto")]
    public partial class MetricsIntervalResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsIntervalResultDto" /> class.
        /// </summary>
        /// <param name="timestamp">The interval timestamp..</param>
        /// <param name="name">The name of the metric..</param>
        /// <param name="reporter">The reporter of the metric. &#x60;null&#x60; if the metrics are aggregated by reporter..</param>
        /// <param name="value">The value of the metric aggregated by the interval..</param>
        public MetricsIntervalResultDto(DateTime? timestamp = default(DateTime?), string name = default(string), string reporter = default(string), long? value = default(long?))
        {
            this.Timestamp = timestamp;
            this.Name = name;
            this.Reporter = reporter;
            this.Value = value;
        }

        /// <summary>
        /// The interval timestamp.
        /// </summary>
        /// <value>The interval timestamp.</value>
        [DataMember(Name = "timestamp", EmitDefaultValue = true)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// The name of the metric.
        /// </summary>
        /// <value>The name of the metric.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The reporter of the metric. &#x60;null&#x60; if the metrics are aggregated by reporter.
        /// </summary>
        /// <value>The reporter of the metric. &#x60;null&#x60; if the metrics are aggregated by reporter.</value>
        [DataMember(Name = "reporter", EmitDefaultValue = true)]
        public string Reporter { get; set; }

        /// <summary>
        /// The value of the metric aggregated by the interval.
        /// </summary>
        /// <value>The value of the metric aggregated by the interval.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public long? Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MetricsIntervalResultDto {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Reporter: ").Append(Reporter).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
