/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// A JSON object corresponding to the Activity Instance tree of the given process instance.
    /// </summary>
    [DataContract(Name = "TransitionInstanceDto")]
    public partial class TransitionInstanceDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransitionInstanceDto" /> class.
        /// </summary>
        /// <param name="id">The id of the transition instance..</param>
        /// <param name="parentActivityInstanceId">The id of the parent activity instance, for example a sub process instance..</param>
        /// <param name="activityId">The id of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job).</param>
        /// <param name="activityName">The name of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job).</param>
        /// <param name="activityType">The type of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job).</param>
        /// <param name="processInstanceId">The id of the process instance this instance is part of..</param>
        /// <param name="processDefinitionId">The id of the process definition..</param>
        /// <param name="executionId">The execution id..</param>
        /// <param name="incidentIds">A list of incident ids..</param>
        /// <param name="incidents">A list of JSON objects containing incident specific properties: * &#x60;id&#x60;: the id of the incident * &#x60;activityId&#x60;: the activity id in which the incident occurred.</param>
        public TransitionInstanceDto(string id = default(string), string parentActivityInstanceId = default(string), string activityId = default(string), string activityName = default(string), string activityType = default(string), string processInstanceId = default(string), string processDefinitionId = default(string), string executionId = default(string), List<string> incidentIds = default(List<string>), List<ActivityInstanceIncidentDto> incidents = default(List<ActivityInstanceIncidentDto>))
        {
            this.Id = id;
            this.ParentActivityInstanceId = parentActivityInstanceId;
            this.ActivityId = activityId;
            this.ActivityName = activityName;
            this.ActivityType = activityType;
            this.ProcessInstanceId = processInstanceId;
            this.ProcessDefinitionId = processDefinitionId;
            this.ExecutionId = executionId;
            this.IncidentIds = incidentIds;
            this.Incidents = incidents;
        }

        /// <summary>
        /// The id of the transition instance.
        /// </summary>
        /// <value>The id of the transition instance.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The id of the parent activity instance, for example a sub process instance.
        /// </summary>
        /// <value>The id of the parent activity instance, for example a sub process instance.</value>
        [DataMember(Name = "parentActivityInstanceId", EmitDefaultValue = true)]
        public string ParentActivityInstanceId { get; set; }

        /// <summary>
        /// The id of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
        /// </summary>
        /// <value>The id of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)</value>
        [DataMember(Name = "activityId", EmitDefaultValue = true)]
        public string ActivityId { get; set; }

        /// <summary>
        /// The name of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
        /// </summary>
        /// <value>The name of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)</value>
        [DataMember(Name = "activityName", EmitDefaultValue = true)]
        public string ActivityName { get; set; }

        /// <summary>
        /// The type of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
        /// </summary>
        /// <value>The type of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)</value>
        [DataMember(Name = "activityType", EmitDefaultValue = true)]
        public string ActivityType { get; set; }

        /// <summary>
        /// The id of the process instance this instance is part of.
        /// </summary>
        /// <value>The id of the process instance this instance is part of.</value>
        [DataMember(Name = "processInstanceId", EmitDefaultValue = true)]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// The id of the process definition.
        /// </summary>
        /// <value>The id of the process definition.</value>
        [DataMember(Name = "processDefinitionId", EmitDefaultValue = true)]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// The execution id.
        /// </summary>
        /// <value>The execution id.</value>
        [DataMember(Name = "executionId", EmitDefaultValue = true)]
        public string ExecutionId { get; set; }

        /// <summary>
        /// A list of incident ids.
        /// </summary>
        /// <value>A list of incident ids.</value>
        [DataMember(Name = "incidentIds", EmitDefaultValue = true)]
        public List<string> IncidentIds { get; set; }

        /// <summary>
        /// A list of JSON objects containing incident specific properties: * &#x60;id&#x60;: the id of the incident * &#x60;activityId&#x60;: the activity id in which the incident occurred
        /// </summary>
        /// <value>A list of JSON objects containing incident specific properties: * &#x60;id&#x60;: the id of the incident * &#x60;activityId&#x60;: the activity id in which the incident occurred</value>
        [DataMember(Name = "incidents", EmitDefaultValue = true)]
        public List<ActivityInstanceIncidentDto> Incidents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransitionInstanceDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ParentActivityInstanceId: ").Append(ParentActivityInstanceId).Append("\n");
            sb.Append("  ActivityId: ").Append(ActivityId).Append("\n");
            sb.Append("  ActivityName: ").Append(ActivityName).Append("\n");
            sb.Append("  ActivityType: ").Append(ActivityType).Append("\n");
            sb.Append("  ProcessInstanceId: ").Append(ProcessInstanceId).Append("\n");
            sb.Append("  ProcessDefinitionId: ").Append(ProcessDefinitionId).Append("\n");
            sb.Append("  ExecutionId: ").Append(ExecutionId).Append("\n");
            sb.Append("  IncidentIds: ").Append(IncidentIds).Append("\n");
            sb.Append("  Incidents: ").Append(Incidents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
