/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// UserCredentialsDto
    /// </summary>
    [DataContract(Name = "UserCredentialsDto")]
    public partial class UserCredentialsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCredentialsDto" /> class.
        /// </summary>
        /// <param name="password">The users new password..</param>
        /// <param name="authenticatedUserPassword">The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter)..</param>
        public UserCredentialsDto(string password = default(string), string authenticatedUserPassword = default(string))
        {
            this.Password = password;
            this.AuthenticatedUserPassword = authenticatedUserPassword;
        }

        /// <summary>
        /// The users new password.
        /// </summary>
        /// <value>The users new password.</value>
        [DataMember(Name = "password", EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).
        /// </summary>
        /// <value>The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).</value>
        [DataMember(Name = "authenticatedUserPassword", EmitDefaultValue = true)]
        public string AuthenticatedUserPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserCredentialsDto {\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  AuthenticatedUserPassword: ").Append(AuthenticatedUserPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
