/*
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.21.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Camunda.OpenApi.Client.Client.FileParameter;
using OpenAPIDateConverter = Camunda.OpenApi.Client.Client.OpenAPIDateConverter;

namespace Camunda.OpenApi.Client.Model
{
    /// <summary>
    /// UserOperationLogEntryDto
    /// </summary>
    [DataContract(Name = "UserOperationLogEntryDto")]
    public partial class UserOperationLogEntryDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserOperationLogEntryDto" /> class.
        /// </summary>
        /// <param name="id">The unique identifier of this log entry..</param>
        /// <param name="userId">The user who performed this operation..</param>
        /// <param name="timestamp">Timestamp of this operation..</param>
        /// <param name="operationId">The unique identifier of this operation. A composite operation that changes multiple properties has a common &#x60;operationId&#x60;..</param>
        /// <param name="operationType">The type of this operation, e.g., &#x60;Assign&#x60;, &#x60;Claim&#x60; and so on..</param>
        /// <param name="entityType">The type of the entity on which this operation was executed, e.g., &#x60;Task&#x60; or &#x60;Attachment&#x60;..</param>
        /// <param name="category">The name of the category this operation was associated with, e.g., &#x60;TaskWorker&#x60; or &#x60;Admin&#x60;..</param>
        /// <param name="annotation">An arbitrary annotation set by a user for auditing reasons..</param>
        /// <param name="property">The property changed by this operation..</param>
        /// <param name="orgValue">The original value of the changed property..</param>
        /// <param name="newValue">The new value of the changed property..</param>
        /// <param name="deploymentId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this deployment..</param>
        /// <param name="processDefinitionId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process definition..</param>
        /// <param name="processDefinitionKey">If not &#x60;null&#x60;, the operation is restricted to entities in relation to process definitions with this key..</param>
        /// <param name="processInstanceId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process instance..</param>
        /// <param name="executionId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this execution..</param>
        /// <param name="caseDefinitionId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case definition..</param>
        /// <param name="caseInstanceId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case instance..</param>
        /// <param name="caseExecutionId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case execution..</param>
        /// <param name="taskId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this task..</param>
        /// <param name="externalTaskId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this external task..</param>
        /// <param name="batchId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this batch..</param>
        /// <param name="jobId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job..</param>
        /// <param name="jobDefinitionId">If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job definition..</param>
        /// <param name="removalTime">The time after which the entry should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.21/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;..</param>
        /// <param name="rootProcessInstanceId">The process instance id of the root process instance that initiated the process containing this entry..</param>
        public UserOperationLogEntryDto(string id = default(string), string userId = default(string), DateTime? timestamp = default(DateTime?), string operationId = default(string), string operationType = default(string), string entityType = default(string), string category = default(string), string annotation = default(string), string property = default(string), string orgValue = default(string), string newValue = default(string), string deploymentId = default(string), string processDefinitionId = default(string), string processDefinitionKey = default(string), string processInstanceId = default(string), string executionId = default(string), string caseDefinitionId = default(string), string caseInstanceId = default(string), string caseExecutionId = default(string), string taskId = default(string), string externalTaskId = default(string), string batchId = default(string), string jobId = default(string), string jobDefinitionId = default(string), DateTime? removalTime = default(DateTime?), string rootProcessInstanceId = default(string))
        {
            this.Id = id;
            this.UserId = userId;
            this.Timestamp = timestamp;
            this.OperationId = operationId;
            this.OperationType = operationType;
            this.EntityType = entityType;
            this.Category = category;
            this.Annotation = annotation;
            this.Property = property;
            this.OrgValue = orgValue;
            this.NewValue = newValue;
            this.DeploymentId = deploymentId;
            this.ProcessDefinitionId = processDefinitionId;
            this.ProcessDefinitionKey = processDefinitionKey;
            this.ProcessInstanceId = processInstanceId;
            this.ExecutionId = executionId;
            this.CaseDefinitionId = caseDefinitionId;
            this.CaseInstanceId = caseInstanceId;
            this.CaseExecutionId = caseExecutionId;
            this.TaskId = taskId;
            this.ExternalTaskId = externalTaskId;
            this.BatchId = batchId;
            this.JobId = jobId;
            this.JobDefinitionId = jobDefinitionId;
            this.RemovalTime = removalTime;
            this.RootProcessInstanceId = rootProcessInstanceId;
        }

        /// <summary>
        /// The unique identifier of this log entry.
        /// </summary>
        /// <value>The unique identifier of this log entry.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The user who performed this operation.
        /// </summary>
        /// <value>The user who performed this operation.</value>
        [DataMember(Name = "userId", EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Timestamp of this operation.
        /// </summary>
        /// <value>Timestamp of this operation.</value>
        [DataMember(Name = "timestamp", EmitDefaultValue = true)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// The unique identifier of this operation. A composite operation that changes multiple properties has a common &#x60;operationId&#x60;.
        /// </summary>
        /// <value>The unique identifier of this operation. A composite operation that changes multiple properties has a common &#x60;operationId&#x60;.</value>
        [DataMember(Name = "operationId", EmitDefaultValue = true)]
        public string OperationId { get; set; }

        /// <summary>
        /// The type of this operation, e.g., &#x60;Assign&#x60;, &#x60;Claim&#x60; and so on.
        /// </summary>
        /// <value>The type of this operation, e.g., &#x60;Assign&#x60;, &#x60;Claim&#x60; and so on.</value>
        [DataMember(Name = "operationType", EmitDefaultValue = true)]
        public string OperationType { get; set; }

        /// <summary>
        /// The type of the entity on which this operation was executed, e.g., &#x60;Task&#x60; or &#x60;Attachment&#x60;.
        /// </summary>
        /// <value>The type of the entity on which this operation was executed, e.g., &#x60;Task&#x60; or &#x60;Attachment&#x60;.</value>
        [DataMember(Name = "entityType", EmitDefaultValue = true)]
        public string EntityType { get; set; }

        /// <summary>
        /// The name of the category this operation was associated with, e.g., &#x60;TaskWorker&#x60; or &#x60;Admin&#x60;.
        /// </summary>
        /// <value>The name of the category this operation was associated with, e.g., &#x60;TaskWorker&#x60; or &#x60;Admin&#x60;.</value>
        [DataMember(Name = "category", EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// An arbitrary annotation set by a user for auditing reasons.
        /// </summary>
        /// <value>An arbitrary annotation set by a user for auditing reasons.</value>
        [DataMember(Name = "annotation", EmitDefaultValue = true)]
        public string Annotation { get; set; }

        /// <summary>
        /// The property changed by this operation.
        /// </summary>
        /// <value>The property changed by this operation.</value>
        [DataMember(Name = "property", EmitDefaultValue = true)]
        public string Property { get; set; }

        /// <summary>
        /// The original value of the changed property.
        /// </summary>
        /// <value>The original value of the changed property.</value>
        [DataMember(Name = "orgValue", EmitDefaultValue = true)]
        public string OrgValue { get; set; }

        /// <summary>
        /// The new value of the changed property.
        /// </summary>
        /// <value>The new value of the changed property.</value>
        [DataMember(Name = "newValue", EmitDefaultValue = true)]
        public string NewValue { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this deployment.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this deployment.</value>
        [DataMember(Name = "deploymentId", EmitDefaultValue = true)]
        public string DeploymentId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process definition.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process definition.</value>
        [DataMember(Name = "processDefinitionId", EmitDefaultValue = true)]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to process definitions with this key.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to process definitions with this key.</value>
        [DataMember(Name = "processDefinitionKey", EmitDefaultValue = true)]
        public string ProcessDefinitionKey { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process instance.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this process instance.</value>
        [DataMember(Name = "processInstanceId", EmitDefaultValue = true)]
        public string ProcessInstanceId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this execution.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this execution.</value>
        [DataMember(Name = "executionId", EmitDefaultValue = true)]
        public string ExecutionId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case definition.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case definition.</value>
        [DataMember(Name = "caseDefinitionId", EmitDefaultValue = true)]
        public string CaseDefinitionId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case instance.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case instance.</value>
        [DataMember(Name = "caseInstanceId", EmitDefaultValue = true)]
        public string CaseInstanceId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case execution.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this case execution.</value>
        [DataMember(Name = "caseExecutionId", EmitDefaultValue = true)]
        public string CaseExecutionId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this task.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this task.</value>
        [DataMember(Name = "taskId", EmitDefaultValue = true)]
        public string TaskId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this external task.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this external task.</value>
        [DataMember(Name = "externalTaskId", EmitDefaultValue = true)]
        public string ExternalTaskId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this batch.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this batch.</value>
        [DataMember(Name = "batchId", EmitDefaultValue = true)]
        public string BatchId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job.</value>
        [DataMember(Name = "jobId", EmitDefaultValue = true)]
        public string JobId { get; set; }

        /// <summary>
        /// If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job definition.
        /// </summary>
        /// <value>If not &#x60;null&#x60;, the operation is restricted to entities in relation to this job definition.</value>
        [DataMember(Name = "jobDefinitionId", EmitDefaultValue = true)]
        public string JobDefinitionId { get; set; }

        /// <summary>
        /// The time after which the entry should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.21/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;.
        /// </summary>
        /// <value>The time after which the entry should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.21/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd&#39;T&#39;HH:mm:ss.SSSZ&#x60;.</value>
        [DataMember(Name = "removalTime", EmitDefaultValue = true)]
        public DateTime? RemovalTime { get; set; }

        /// <summary>
        /// The process instance id of the root process instance that initiated the process containing this entry.
        /// </summary>
        /// <value>The process instance id of the root process instance that initiated the process containing this entry.</value>
        [DataMember(Name = "rootProcessInstanceId", EmitDefaultValue = true)]
        public string RootProcessInstanceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserOperationLogEntryDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  OperationId: ").Append(OperationId).Append("\n");
            sb.Append("  OperationType: ").Append(OperationType).Append("\n");
            sb.Append("  EntityType: ").Append(EntityType).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Annotation: ").Append(Annotation).Append("\n");
            sb.Append("  Property: ").Append(Property).Append("\n");
            sb.Append("  OrgValue: ").Append(OrgValue).Append("\n");
            sb.Append("  NewValue: ").Append(NewValue).Append("\n");
            sb.Append("  DeploymentId: ").Append(DeploymentId).Append("\n");
            sb.Append("  ProcessDefinitionId: ").Append(ProcessDefinitionId).Append("\n");
            sb.Append("  ProcessDefinitionKey: ").Append(ProcessDefinitionKey).Append("\n");
            sb.Append("  ProcessInstanceId: ").Append(ProcessInstanceId).Append("\n");
            sb.Append("  ExecutionId: ").Append(ExecutionId).Append("\n");
            sb.Append("  CaseDefinitionId: ").Append(CaseDefinitionId).Append("\n");
            sb.Append("  CaseInstanceId: ").Append(CaseInstanceId).Append("\n");
            sb.Append("  CaseExecutionId: ").Append(CaseExecutionId).Append("\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  ExternalTaskId: ").Append(ExternalTaskId).Append("\n");
            sb.Append("  BatchId: ").Append(BatchId).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  JobDefinitionId: ").Append(JobDefinitionId).Append("\n");
            sb.Append("  RemovalTime: ").Append(RemovalTime).Append("\n");
            sb.Append("  RootProcessInstanceId: ").Append(RootProcessInstanceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
